# A Definition of Causal Effect {#sec-1}

독자가 이미 인과 효과가 무엇인지 알고 있으며 연관성과 인과성의 차이를 이해하고 있다고 가정한다. 이 챕터의 목적은 이미 가지고 있는 인과적 직관을 형식화 하는 수학적 표기법을 알아보는 것이다. 

## Individual Causal Effects {#sec-11}

우리는 어떤 조치 $A$가 취해졌을 때의 결과와 $A$가 취해지지 않았을 때의 결과를 비교하여 두 결과가 다르면, $A$에 인과 효과가 있다고 말한다. 여기서 $A$를 간섭(intervention) 또는 exposure, policy, treatment라고 부른다. 

인과적 직관을 분석에 적용하기 위한 표기법을 알아보자. 우선 binary treatment $A$(1: treated, 0: untreated), binary outcome $Y$(1: death, 0: survival)를 고려하자. $A$와 $Y$는 random variables이다. $Y^{a=1}$는 처리 $a=1$ 하에서 관찰되는 outcome 변수이고, $Y^{a=0}$는 처리 $a=0$ 하에서 관찰되는 outcome 변수다. 여기서 $Y^{a=1}$과 $Y^{a=0}$도 random variables다. 

이제 개개인에 대한 인과 효과를 정의내릴 수 있다: 만일 개인에 대해 $Y^{a=1}\ne Y^{a=0}$이라면, 처리 $A$가 outcome $Y$에 인과 효과가 있는 것이다. 여기서 변수 $Y^{a=1}$과 $Y^{a=0}$를 **잠재적 결과(potential outcomes) 또는 반사실적 결과(counterfactual outcomes)**라고 부른다. 

- 실제로 관찰될 수 있는 두 결과 중 하나라는 의미에서 '잠재적 결과'
- 사실에 반하는 상황을 나타내는 의미에서 '반사실적 결과'

각 개인에 대해 반사실적 결과 중 하나는 실제로 사실이다. 예를 들어, 제우스가 실제로 치료를 받았기 때문에($A=1$), 그의 치료 하에서의 반사실적 결과 $Y^{a=1}=1$는 그것의 관찰된 실제 결과 $Y=1$와 같다. 이는 $Y=Y^A$와 같이 간결하게 표현할 수 있다. 여기서 $Y^A$는 개인의 관찰된 처리 $A$에 해당하는 값 $a$에서 평가된 반사실적 $Y$를 나타낸다. 이를 **일관성(consistency)**이라고 한다.

::: {.callout-tip}
## Consistency

$Y^a_i=Y^A_i=Y_i$ if $A_i=a$
:::

개별 인과 효과는 반사실적 결과(counterfactual outcome) 값과의 대조로써 정의되지만, 각 개인에 대해 관찰되는 것은 outcomes 중 하나뿐이다 - 개인이 실제로 경험한 처리 값에 해당하는 것이다. 다른 모든 반사실적 결과는 관찰되지 않는다. 누락된 데이터로 인해 개별 효과는 식별할 수 없다. 즉, 관찰된 데이터의 함수로 표현할 수 없다는 것이다. 